-- MySQL Script generated by MySQL Workbench
-- Wed May  8 18:23:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`),
  UNIQUE INDEX `cod_pessoa_UNIQUE` (`cod_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabricante` (
  `cod_fabricante` INT NOT NULL,
  `nome_fabricante` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_fabricante`),
  UNIQUE INDEX `nome_fabricante_UNIQUE` (`nome_fabricante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_veiuclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_veiuclo` (
  `cod_modelo` INT NOT NULL,
  `descricao_modelo` VARCHAR(45) NULL,
  `fabricante_cod_fabricante` INT NOT NULL,
  PRIMARY KEY (`cod_modelo`),
  UNIQUE INDEX `descricao_modelo_UNIQUE` (`descricao_modelo` ASC) VISIBLE,
  INDEX `fk_modelo_veiuclo_fabricante_idx` (`fabricante_cod_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_veiuclo_fabricante`
    FOREIGN KEY (`fabricante_cod_fabricante`)
    REFERENCES `mydb`.`fabricante` (`cod_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_veiculo` (
  `cod_venda` INT NOT NULL,
  `data_venda` DATE NULL,
  `valor_venda` DECIMAL(10,2) NULL,
  PRIMARY KEY (`cod_venda`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
