-- MySQL Script generated by MySQL Workbench
-- Sun May 12 08:19:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `cod_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_vendedor` (
  `cod_vendedor` INT NOT NULL AUTO_INCREMENT,
  `vendedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_venda` (
  `cod_venda` INT NOT NULL AUTO_INCREMENT,
  `cod_produto` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  `cod_vendedor` INT NOT NULL,
  `data_compra` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_produto` DECIMAL(10,2) NOT NULL,
  `valor_venda` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`cod_venda`),
  UNIQUE INDEX `cod_venda_UNIQUE` (`cod_venda` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_produto_idx` (`cod_produto` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_estado1_idx` (`cod_estado` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_vendedor1_idx` (`cod_vendedor` ASC) VISIBLE,
  UNIQUE INDEX `cod_produto_UNIQUE` (`cod_produto` ASC) VISIBLE,
  UNIQUE INDEX `cod_estado_UNIQUE` (`cod_estado` ASC) VISIBLE,
  UNIQUE INDEX `cod_vendedor_UNIQUE` (`cod_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_produto`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `mydb`.`tb_produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `mydb`.`tb_estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_vendedor1`
    FOREIGN KEY (`cod_vendedor`)
    REFERENCES `mydb`.`tb_vendedor` (`cod_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
